### ISSUE TITLE
Incorrectly used radio-buttons

### ISSUE THREAD

**Issue by Boyan-Apostolov** [Berat-Dzhevdetov/Fake-Filler#2]
Hello, amazing and useful extension, great job. 
However, I've found a bug when using radio-buttons and would like to report it.
Type "Radio" - In your method `chooseRadio(radios)`, you are iterating over all input type-radio's and are adding the ones with unique names to the array `unique`. (I suppose you are doing that because fields like gender M/F have the same name attribute). However, if (for some reason) the radio buttons dont have a name attribute, they do not get added to the array and then the logic over the iteration of that array bugges out. (Pic for reference) 

![image](https://user-images.githubusercontent.com/58187770/187742431-87dccf2f-0316-46eb-abb7-105205b1e00f.png)

Note: I have to click the extension a few times for the error to occur.
Thats just a weird case scenario, everything else is perfect:)

**Comment by Berat-Dzhevdetov** [comment]
Thank you! I'll have a look when possible.
